var zoomControlsWrapper;
var map;
var galleryData;
var galleryMarkers;
var baseMarkerSize;
var markerOptions;
var chartColors;
var galleryMetaData;
var currentCategory;
var colorBoard;
var currentListSelectedID = null;
var controlDiv = null;
var control2Div = null;
var mapControlsDiv = null;
var directionsDisplay;
var directionsService;
var infoBubble;
var restaurantData;
var barData;
var restaurantMarkers;
var barMarkers;
var markerVisibility;
var markerProfileHeight;